# Generated by Django 5.0.3 on 2024-05-05 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('study_method', models.CharField(choices=[('ONLINE', 'online'), ('PHYSICAL', 'physical')], default='online', max_length=50)),
                ('duration', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('more_info', models.TextField()),
                ('picture', models.FileField(null=True, upload_to='courses')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Course',
            fields=[
                ('sub_course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('study_method', models.CharField(choices=[('ONLINE', 'online'), ('PHYSICAL', 'physical')], default='online', max_length=50)),
                ('duration', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('more_info', models.TextField()),
                ('picture', models.FileField(null=True, upload_to='sub_courses')),
                ('date', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='sub_course')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.FileField(null=True, upload_to='all_courses')),
                ('couse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='pics')),
                ('sub_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.sub_course', verbose_name='pics')),
            ],
        ),
    ]
