# Generated by Django 5.0.3 on 2024-05-01 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_order', '0001_initial'),
        ('courses', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='course_cartitem',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='course_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course_ordereditem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='course_ordereditem',
            name='course',
        ),
        migrations.CreateModel(
            name='Orderd_course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderd_course', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Cart',
        ),
        migrations.DeleteModel(
            name='Course_CartItem',
        ),
        migrations.DeleteModel(
            name='Course_Order',
        ),
        migrations.DeleteModel(
            name='Course_OrderedItem',
        ),
    ]
